name: material_widgets
description: An package of widgets conforming to the material design spec.
version: 0.4.0-preview.9
homepage: https://github.com/kalildev/material_widgets

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0
  meta: ^1.2.4
  collection: ^1.14.0
  material_you: ^0.0.32
  shape_theme_switcher: ^0.0.3
  flutter_monet_theme: ^0.4.3
  dynamic_color_compat: ^0.0.2

dev_dependencies:
  demostudo_lint: ^1.0.2
  flutter_test:
    sdk: flutter
