name: material_widgets
description: An package of widgets conforming to the material design spec.
version: 0.4.0-preview.2
author: KalilDev
# homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  breakpoint: ^1.0.1+2
  smooth_page_indicator: ^0.2.0
  meta: ^1.2.4
  collection: ^1.14.0
  material_you: ^0.0.18
  shape_theme_switcher: ^0.0.3
  flutter_monet_theme:

dev_dependencies:
  demostudo_lint: ^1.0.2
  flutter_test:
    sdk: flutter
