name: material_widgets
description: An package of widgets conforming to the material design spec.
version: 0.1.0
author: KalilDev
# homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  breakpoint: ^1.0.1+2
  smooth_page_indicator: ^0.2.0
  meta: ^1.2.4
  collection: ^1.14.0

dev_dependencies:
  demostudo_lint:
    path: ../../demostudo_lint
  flutter_test:
    sdk: flutter
